name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # or 'master' depending on your repo

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # upload everything (index.html, assets/, lessons/, etc.)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
